### ISSUE TITLE
Usage section

### ISSUE THREAD

**Issue by Atinux** [Mini-ghost/nuxt-svgo-loader#1]
Hi! Thanks for the Nuxt module!

Would it be possible to add a Usage section in the readme?

Also, the playground seems to not work on Stackblitz: https://stackblitz.com/github/Mini-ghost/nuxt-svgo-loader/tree/main?file=README.md

I think it would also be nice to make it working + link in the readme as well as showing an example (seems the index page is empty)

**Comment by Mini-ghost** [comment]
Hi! Thank you for your feedback and for bringing these points to my attention. I've addressed the issue with the playground on Stackblitz and ensured that it now works properly. Additionally, I've added a Usage section in the readme to provide clear guidance on how to use the Nuxt module.

Stackblitz: https://stackblitz.com/github/Mini-ghost/nuxt-svgo-loader/tree/main?file=README.md

I'd also like to extend my gratitude to the Nuxt core team for providing us with such an exceptional framework. It's truly a pleasure to work with Nuxt.
